# Generated by Django 4.0.6 on 2022-07-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Authors name')),
                ('birth_date', models.DateTimeField(verbose_name='Date of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Book name')),
                ('page_number', models.IntegerField()),
                ('pub_date', models.DateField(verbose_name='Release date')),
            ],
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(choices=[('SOFT', 'SOFTBACK'), ('HARD', 'HARDBACK')], default='SOFT', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('SCI-FI', 'SCI-FI'), ('ACTION', 'ACTION'), ('FANTASY', 'FANTASY'), ('THILER', 'THILER'), ('OTHER', 'OTHER')], default='OTHER', max_length=20, verbose_name='Is this book authors first book:')),
                ('book', models.ManyToManyField(to='book_store.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors_first_book', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3, verbose_name='Is this book authors first book:')),
                ('authors_award_for_book', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=3, verbose_name='Recieved author prize for this book:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.cover'),
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(through='book_store.BookAuthor', to='book_store.book'),
        ),
    ]
