# Generated by Django 4.0.6 on 2022-07-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='books',
            new_name='book',
        ),
    ]
