# Generated by Django 4.0.6 on 2022-07-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_rename_books_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
