# Generated by Django 4.0.6 on 2022-07-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_alter_author_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gendre',
            name='gender',
            field=models.CharField(choices=[('SCI-FI', 'SCI-FI'), ('ACTION', 'ACTION'), ('FANTASY', 'FANTASY'), ('THILER', 'THILER'), ('OTHER', 'OTHER')], default='OTHER', max_length=20, verbose_name='Gender of book:'),
        ),
    ]
