# Generated by Django 4.0.6 on 2022-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_alter_gendre_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('SCI-FI', 'SCI-FI'), ('ACTION', 'ACTION'), ('FANTASY', 'FANTASY'), ('THILER', 'THILER'), ('OTHER', 'OTHER')], default='OTHER', max_length=20, verbose_name='Genre of book:')),
                ('book', models.ManyToManyField(to='book_store.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Gendre',
        ),
    ]
