# Generated by Django 4.0.6 on 2022-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_genre_delete_gendre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book_store.genre'),
        ),
    ]
