# Generated by Django 4.0.6 on 2022-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_cover_signed_by_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='cover',
            field=models.CharField(choices=[('SOFT', 'SOFTBACK'), ('HARD', 'HARDBACK'), ('SOFT SIGNED', 'SOFTBACK SIGNED'), ('HARD SIGNED', 'HARDBACK SIGNED')], default='SOFT', max_length=200),
        ),
        migrations.AlterField(
            model_name='cover',
            name='signed_by_author',
            field=models.BooleanField(default=False),
        ),
    ]
