# Generated by Django 4.0.6 on 2022-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0009_alter_bookauthor_authors_award_for_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book',
            new_name='book_name',
        ),
        migrations.AddField(
            model_name='book',
            name='authors_name',
            field=models.ManyToManyField(through='book_store.BookAuthor', to='book_store.author'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='authors_award_for_book',
            field=models.BooleanField(default=False, verbose_name='The author has received an award for this book.'),
        ),
        migrations.AlterField(
            model_name='bookauthor',
            name='authors_first_book',
            field=models.BooleanField(default=False, verbose_name='This is authors first book.'),
        ),
    ]
