# Generated by Django 4.0.6 on 2022-07-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0010_rename_book_author_book_name_book_authors_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='book_name',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors_name',
        ),
    ]
