# Generated by Django 4.0.6 on 2022-07-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0011_rename_book_name_author_book_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('authors_first_book', True)), fields=('authors_first_book',), name='unique_authors_first_book'),
        ),
    ]
