# Generated by Django 4.0.6 on 2022-07-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0012_bookauthor_unique_authors_first_book'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookauthor',
            name='unique_authors_first_book',
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('authors_first_book', True)), fields=('author', 'authors_first_book'), name='unique_authors_first_book'),
        ),
    ]
