# Generated by Django 4.0.6 on 2022-07-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0013_remove_bookauthor_unique_authors_first_book_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookauthor',
            name='unique_authors_first_book',
        ),
    ]
